/// @notice Race metadata loader — reads the race-data.json generated by fetch-races + create-markets

import { readFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Try multiple paths for the metadata file
const PATHS = [
  join(__dirname, "..", "data", "race-metadata.json"),
  join(__dirname, "..", "..", "frontend", "src", "lib", "race-data.json"),
];

let raceData = {};

for (const p of PATHS) {
  if (existsSync(p)) {
    try {
      raceData = JSON.parse(readFileSync(p, "utf-8"));
      console.log(`[metadata] Loaded ${Object.keys(raceData).length} races from ${p}`);
      break;
    } catch (e) {
      console.warn(`[metadata] Failed to parse ${p}:`, e.message);
    }
  }
}

if (Object.keys(raceData).length === 0) {
  console.warn("[metadata] No race metadata found. Run 'npm run fetch-races' and 'npm run create-markets' first.");
}

/**
 * Get race metadata by raceId (bytes32 hash).
 * Returns null if no metadata exists for this race.
 */
export function getRaceMetadata(raceId) {
  return raceData[raceId] || null;
}

/**
 * Get all race metadata.
 */
export function getAllRaceMetadata() {
  return raceData;
}
